### ISSUE TITLE
When I tried multiple face recognition, an error occurred

### ISSUE THREAD

**Issue by dongg622** [kwea123/VTuber_Unity#10]
Thank you for your excellent work,When I tried multiple face recognition, an error occurred,like this
![微信图片_20200724094436](https://user-images.githubusercontent.com/49979601/88354247-ea6aab80-cd92-11ea-88fa-481bf7f629aa.png)
how to solve this problem

**Comment by kwea123** [comment]
This project only works for one face. If you want to apply for multiple faces you need to modify the code (a lot of things).

**Comment by dongg622** [comment]
I got it
Not that complicated
Just create a stabilizer for each face separately
![微信图片_20200727110505](https://user-images.githubusercontent.com/49979601/88499835-a200f700-cff9-11ea-9c61-d05f27639ed6.png)
