### ISSUE TITLE
ace_alignment/ckpts

### ISSUE THREAD

**Issue by Hocemedinbg** [kwea123/VTuber_Unity#2]
Sorry I'm a beginner, I would like to ask : When you say "You need to download the models here, extract and put into face_alignment/ckpts" does that mean that I must create a folder named "ckpts" under "face_alignment" and copy the files to it ?

**Comment by kwea123** [comment]
yes. After download and extract you should have this
![Untitled](https://user-images.githubusercontent.com/11364490/72430948-f15aa500-37d6-11ea-9698-f759d4c5615d.png)
