### ISSUE TITLE
about cpu and gpu speed

### ISSUE THREAD

**Issue by ShunyuYao** [kwea123/VTuber_Unity#3]
Very excellet job! I have one question. Why your cpu model runs much more faster than gpu model showed in your home page(cpu 200fps, gpu 30 fps). Typically, gpu runs more faster than cpu.
![image](https://user-images.githubusercontent.com/33683262/73850249-4f265e00-4866-11ea-9d3d-3a9980534c02.png)

**Comment by ShunyuYao** [comment]
![image](https://user-images.githubusercontent.com/33683262/73850377-88f76480-4866-11ea-9fc0-587d59eb8e7f.png)

**Comment by kwea123** [comment]
It's not the same model. CPU version uses a lighter model which is provided by `dlib`. I didn't look into it but maybe it's not even a deep learning model, so it runs a lot faster.

**Comment by ShunyuYao** [comment]
Got it. Thanks!
