### ISSUE TITLE
Demo.py throw exceptions.UnboundLocalError

### ISSUE THREAD

**Issue by Guangpop** [kwea123/VTuber_Unity#4]
Hello, I am studying your project, and encounter crush by running demo.py 

line 119:                
if frame_count == 1 or frame_count % 2 == 0: 
                                                                           
In my environment, webcam may started later than python thread, therefore, the first frame may not
be 1 in this line.

My solution: add length check for prev_marks

if len(prev_marks) == 0 or frame_count == 1 or frame_count % 2 == 0:

Thanks

**Comment by kwea123** [comment]
It seems to be compatible with the current code. Fix is applied. Thank you very much.
Please do not hesitate to ask for fix if other problems occur.
