### ISSUE TITLE
linux unity problem

### ISSUE THREAD

**Issue by wuboris** [kwea123/VTuber_Unity#6]
Set current directory to /root/intel/linux_x86_64
Found path: /root/intel/linux_x86_64/unitychan.x86_64
Mono path[0] = '/root/intel/linux_x86_64/unitychan_Data/Managed'
Mono config path = '/root/intel/linux_x86_64/unitychan_Data/MonoBleedingEdge/etc'
Preloaded 'ScreenSelector.so'
Display 0 '0': 2048x1112 (primary device).
Logging to /root/.config/unity3d/Editor/Player.log

i use linux with out UI，and use chmod 777 to run the unitychan.x86_64， but it shows information above， no window shows on my Xmanager，the program just shutdown immediately. do you know what can i do?

**Comment by kwea123** [comment]
Hi, I didn't test linux without UI, so maybe it just doesn't work without UI... This project aims to show a character synchronized on the screen, so I think UI is indispensable. Is there any specific reason you use it without UI?

**Comment by wuboris** [comment]
i am trying to use this program to convert humanvideo to anime video，it is convenience for me to use linux for this function. maybe i should try another method.

**Comment by kwea123** [comment]
In my opinion this project doesn't fit your need, maybe try [vid2vid](https://github.com/NVIDIA/vid2vid)

**Comment by wuboris** [comment]
great! thank you
