### ISSUE TITLE
WinError 10053

### ISSUE THREAD

**Issue by sarsembin** [kwea123/VTuber_Unity#7]
So when I write "python demo.py --connect --debug", the python script starts working for a few seconds, and i can actually see my face being capture by camera, but a few seconds later it throws an error. 

0.069 Traceback (most recent call last):
  File "demo.py", line 224, in <module>
    main()
  File "demo.py", line 95, in main
    s.send(bytes(msg, "utf-8"))
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine.

So this happens when it sends data to unitychan. I checked via "netstat -ab" in cmd, that unitychan actually starts to listen the 5066 port on localhost.

I have already tried:
-starting script after a PC reboot and/or without internet connection
-tried to enter script both via cmd and Windows PowerShell, and starting them as an Administrator
-opened port 5066 in Windows Firewall, deleted antivirus
-i also tried to use another port (changed port value both in python and in unity c#, and also opened it in Firewall)

It only happens on windows, i have windows 10 ltsc 1809. When i created virtual machine via Oracle VirtualBox on Ubuntu 18.04, there was no error, but i can't use GPU to run python script on VirtualMachine, so i really want it to work on widows.

**Comment by kwea123** [comment]
What is your python version? Did you install via anaconda like in the readme?

**Comment by sarsembin** [comment]
Yes i did install via anaconda, like in readme file, the python version 3.7.7 in my enviroment.

**Comment by sarsembin** [comment]
tried to run it on python 3.6.10, still doesn't work

**Comment by sarsembin** [comment]
So i managed to fix it. Changed RecieveData() function is Blinker.cs in Unity.

This is changed version.

private void ReceiveData() //TCP LISTENER
        {
            try
            {
                listener = new TcpListener(IPAddress.Parse("127.0.0.1"), port);
                listener.Start();
                Byte[] bytes = new Byte[1024];
                while (true)
                {
                    client = listener.AcceptTcpClient();

                    NetworkStream stream = client.GetStream();
                        
                    int length;
                    while ((length = stream.Read(bytes, 0, bytes.Length)) != 0)
                    {
                        CultureInfo ci = (CultureInfo)CultureInfo.CurrentCulture.Clone();
                        ci.NumberFormat.CurrencyDecimalSeparator = ".";

                        var incommingData = new byte[length];
                        Array.Copy(bytes, 0, incommingData, 0, length);
                        string clientMessage = Encoding.ASCII.GetString(incommingData);
                        string[] res = clientMessage.Split(' ');
                        roll = float.Parse(res[0], NumberStyles.Any, ci) * 0.4f + roll * 0.6f;
                        pitch = float.Parse(res[1], NumberStyles.Any, ci) * 0.4f + pitch * 0.6f;
                        yaw = float.Parse(res[2], NumberStyles.Any, ci) * 0.4f + yaw * 0.6f;
                        min_ear = float.Parse(res[3], NumberStyles.Any, ci);
                        mar = float.Parse(res[4], NumberStyles.Any, ci) * 0.4f + mar * 0.6f;
                        mdst = float.Parse(res[5], NumberStyles.Any, ci);
                    }
                        
                    
                }
            }
            catch (Exception e)
            {
                print(e.ToString());
            }
        }

**Comment by sarsembin** [comment]
So i managed to fix it. Changed RecieveData() function is Blinker.cs in Unity.

This is changed version.
`private void ReceiveData() //TCP LISTENER
{
try
{
listener = new TcpListener(IPAddress.Parse("127.0.0.1"), port);
listener.Start();
Byte[] bytes = new Byte[1024];
while (true)
{
client = listener.AcceptTcpClient();

                NetworkStream stream = client.GetStream();
                    
                int length;
                while ((length = stream.Read(bytes, 0, bytes.Length)) != 0)
                {
                    CultureInfo ci = (CultureInfo)CultureInfo.CurrentCulture.Clone();
                    ci.NumberFormat.CurrencyDecimalSeparator = ".";

                    var incommingData = new byte[length];
                    Array.Copy(bytes, 0, incommingData, 0, length);
                    string clientMessage = Encoding.ASCII.GetString(incommingData);
                    string[] res = clientMessage.Split(' ');
                    roll = float.Parse(res[0], NumberStyles.Any, ci) * 0.4f + roll * 0.6f;
                    pitch = float.Parse(res[1], NumberStyles.Any, ci) * 0.4f + pitch * 0.6f;
                    yaw = float.Parse(res[2], NumberStyles.Any, ci) * 0.4f + yaw * 0.6f;
                    min_ear = float.Parse(res[3], NumberStyles.Any, ci);
                    mar = float.Parse(res[4], NumberStyles.Any, ci) * 0.4f + mar * 0.6f;
                    mdst = float.Parse(res[5], NumberStyles.Any, ci);
                }
                    
                
            }
        }
        catch (Exception e)
        {
            print(e.ToString());
        }
    }`

**Comment by sarsembin** [comment]
So i managed to fix this issue. Changed the RecieveData() function in Blinker.cs in Unity.

        private void ReceiveData() //TCP LISTENER
        {
            try
            {
                listener = new TcpListener(IPAddress.Parse("127.0.0.1"), port);
                listener.Start();
                Byte[] bytes = new Byte[1024];
                while (true)
                {
                    client = listener.AcceptTcpClient();

                    NetworkStream stream = client.GetStream();
                        
                    int length;
                    while ((length = stream.Read(bytes, 0, bytes.Length)) != 0)
                    {
                        CultureInfo ci = (CultureInfo)CultureInfo.CurrentCulture.Clone();
                        ci.NumberFormat.CurrencyDecimalSeparator = ".";

                        var incommingData = new byte[length];
                        Array.Copy(bytes, 0, incommingData, 0, length);
                        string clientMessage = Encoding.ASCII.GetString(incommingData);
                        string[] res = clientMessage.Split(' ');
                        roll = float.Parse(res[0], NumberStyles.Any, ci) * 0.4f + roll * 0.6f;
                        pitch = float.Parse(res[1], NumberStyles.Any, ci) * 0.4f + pitch * 0.6f;
                        yaw = float.Parse(res[2], NumberStyles.Any, ci) * 0.4f + yaw * 0.6f;
                        min_ear = float.Parse(res[3], NumberStyles.Any, ci);
                        mar = float.Parse(res[4], NumberStyles.Any, ci) * 0.4f + mar * 0.6f;
                        mdst = float.Parse(res[5], NumberStyles.Any, ci);
                    }  
                }
            }
            catch (Exception e)
            {
                print(e.ToString());
            }
        }

**Comment by kwea123** [comment]
which lines did you change? You add `Cultureinfo`?

**Comment by sarsembin** [comment]
Yes i added `CultureInfo`, and added it in functions `float.Parse`. It somehow fixed the problem with WinError 10053, but now i encountered another problem. Everything works and 3D model starts to copy my movements, but only when i im in Unity Editor (When i click "play" button there, above the scene with 3D model). When i Bulid it, and open it as usual (Like bianry files that u have here on your github), it just don't want to move (Copy my movements), but the python code is working, there is no Errors occuring, and Blinker.cs is actually running, because i can see the 3D model blinking.

**Comment by sarsembin** [comment]
So right now the model started to work, even in the Build state. I just tried to run it as Administrator. Now everything works fine on windows. Im very happy right now. >.<

**Comment by kwea123** [comment]
Glad you find the solution!
